FROM node:20-alpine AS build
WORKDIR /app

# Define Build Arguments
ARG VITE_INTERNAL_API_KEY
ARG VITE_API_URL

# Set them as Environment Variables for the build process
ENV VITE_INTERNAL_API_KEY=$VITE_INTERNAL_API_KEY
ENV VITE_API_URL=$VITE_API_URL

COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# --- Stage 2: Serve ---
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]